[env:matrix-portal-s3]
platform = espressif32
board = adafruit_matrixportal_esp32s3
framework = arduino
lib_deps =
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.0
    adafruit/Adafruit GFX Library@^1.11.0
    bblanchon/ArduinoJson@^7.0.0
    mathieucarbou/ESPAsyncWebServer@^3.6.0
    mathieucarbou/AsyncTCP@^3.3.0
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
board_build.filesystem = littlefs
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -std=gnu++17
monitor_speed = 115200
upload_speed = 921600
