[env:matrix-portal-s3]
platform = espressif32
board = adafruit_matrixportal_s3
framework = arduino
lib_deps =
    mrcodetastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.0
    bblanchon/ArduinoJson@^7.0.0
    me-no-dev/AsyncTCP@^1.1.1
    me-no-dev/ESPAsyncWebServer@^1.2.3
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
board_build.filesystem = littlefs
build_flags =
    -DBOARD_HAS_PSRAM
    -std=gnu++17
monitor_speed = 115200
upload_speed = 921600
